name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'Flow.Launcher.Plugin.WireGuard/plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Build
        run: |
          dotnet publish 'Flow.Launcher.Plugin.WireGuard/Flow.Launcher.Plugin.WireGuard.csproj' --framework net7.0-windows  -c Release -o "WireGuard"
          7z a -tzip "Flow.Launcher.Plugin.WireGuard.zip" "WireGuard/*"
          rm -r "WireGuard"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Launcher.Plugin.WireGuard.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
